services:
  - type: web
    name: astrochart-engine-api
    runtime: python
    plan: free
    autoDeploy: true  # Set to true if you want GitHub pushes to auto-deploy
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT